name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-manager: ['npm']
        directory: ['frontend', 'backend', 'contracts']
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Check for updates
        uses: MeilCli/npm-update-check-action@v4
        id: check
        with:
          working_directory: ${{ matrix.directory }}
      
      - name: Create Pull Request
        if: steps.check.outputs.has_update == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update dependencies in ${{ matrix.directory }}"
          title: "chore(deps): update ${{ matrix.directory }} dependencies"
          body: |
            Update dependencies in ${{ matrix.directory }}
            
            Updated dependencies:
            ${{ steps.check.outputs.update_dependencies }}
            
            Auto-generated by GitHub Actions
          branch: "deps/update-${{ matrix.directory }}"
          base: "develop"
          labels: "dependencies,automated pr"
      
      - name: Run security audit
        run: |
          cd ${{ matrix.directory }}
          npm audit
        continue-on-error: true
      
      - name: Check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          args: --file=${{ matrix.directory }}/package.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  notify:
    needs: update-dependencies
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      - name: Create issue for failed updates
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Dependency update failed',
              body: 'The automated dependency update workflow has failed. Please check the workflow logs.',
              labels: ['dependencies', 'bug']
            })
