name: Smart Contract CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'contracts/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'contracts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: contracts/package-lock.json
      
      - name: Install dependencies
        run: cd contracts && npm ci
      
      - name: Run Hardhat tests
        run: cd contracts && npx hardhat test
      
      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        with:
          target: contracts/
          slither-args: --exclude naming-convention,external-function,solc-version

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: cd contracts && npm ci
      
      - name: Deploy contracts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          AMOY_RPC_URL: ${{ secrets.AMOY_RPC_URL }}
        run: cd contracts && npx hardhat run scripts/deploy.js --network amoy
